apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kraft-frontend
    project: kraft
  name: kraft-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraft-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kraft-frontend
    spec:
      containers:
      - image: {{.Values.images.frontend}}
        name: kraft-frontend
        ports:
        - containerPort: 80
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kraft-frontend
  name: kraft-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kraft-frontend
status:
  loadBalancer: {}
