{{- $existing := (lookup "v1" "Secret" .Release.Namespace "jwtsecret") }}
{{- $jwtSecret := (randAlphaNum 32) -}}
{{- if $existing -}}
  {{- $jwtSecret = (index $existing.data "JWT_SECRET" | b64dec) -}}
{{- end -}}
apiVersion: v1
data:
  JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: jwtsecret

---

{{- if  .Values.ntfy.enabled }}
apiVersion: v1
data:
  NTFY_URL: {{.Values.ntfy.url | b64enc | quote}}
  NTFY_TOPIC: {{.Values.ntfy.topic | b64enc | quote}}
  NTFY_BASIC_AUTH: {{.Values.ntfy.basicAuth | b64enc | quote}}
  NTFY_TOKEN: {{.Values.ntfy.token | b64enc | quote}}

kind: Secret
metadata:
  creationTimestamp: null
  name: ntfysecret
{{- end }}
