database:
  existingSecret: "kraft-db-secret"
  # database: "kraft"
  # host: "kraft-db"
  # password: dontuseme
  # rootPassword: changeme
  # port: 5432
  # user: kraft

clusterResources:
  servers:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 400m
      memory: 600Mi
  workers:
    requests:
      cpu: 30m
      memory: 75Mi
    limits:
      cpu: 30m
      memory: 75Mi

networking:
  clusterIssuer: "staging-cluster-issuer"
  issuer: "staging-issuer"
  ingressClassName: "traefik"

images:
  frontend: "ghcr.io/xelab04/kraft-frontend:latest"
  core: "ghcr.io/xelab04/kraft-core:latest"

workspaces:
  # you might want to disable the bottomless pit of vulnerabilities
  enabled: true

ntfy:
  enabled: false
  url: "https://notify.alexbissessur.dev"
  topic: "kraft"
  basicAuth: "dXNlcm5hbWU6cGFzc3dvcmQ="
  token: "somekindatoken"

config:
  environment: "PROD"
  host: "kraftcloud.dev"
  betacode: "ENABLED"
  workspacesEnabled: false
