apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kraft-auth
  name: kraft-auth
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kraft-auth
status:
  loadBalancer: {}
