FROM registry.suse.com/bci/rust:1.90 AS build

WORKDIR /app

RUN zypper -n in openssl-devel
RUN cargo install cargo-chef

COPY Cargo.lock Cargo.toml ./
RUN mkdir src
RUN touch src/main.rs
RUN cargo chef prepare --recipe-path recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY . ./

RUN cargo build --release

FROM registry.suse.com/bci/bci-base:latest

RUN zypper -n in openssl-devel

COPY --from=build /app/target/release/auth-api /usr/local/bin/auth-api

EXPOSE 5000

CMD ["auth-api"]
