FROM registry.suse.com/bci/rust:1.90 AS build

WORKDIR /app

RUN zypper -n in openssl-devel

RUN cargo init
COPY Cargo.toml Cargo.lock ./
RUN cargo build --release

COPY . ./

RUN cargo build --release

FROM registry.suse.com/bci/bci-base:latest

RUN zypper -n in openssl-devel

COPY --from=build /app/target/release/auth-api /usr/local/bin/auth-api

EXPOSE 5000

CMD ["auth-api"]
