apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: kraft-cluster-manage
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "200"
spec:
  rules:
  - host: kraft.alexbissessur.dev
    http:
      paths:
      - backend:
          service:
            name: kraft-cluster-manage
            port:
              number: 5000
        path: /api/
        pathType: Prefix
status:
  loadBalancer: {}
