# This is the init container which runs the create.sql

FROM registry.opensuse.org/opensuse/mariadb-client:11.8

WORKDIR /app

COPY create.sql .

# etc etc
# this one is lame, i don't think this is urgent
# bleh
