apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: kraft-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  rules:
  - host: kraft.alexbissessur.dev
    http:
      paths:
      - backend:
          service:
            name: kraft-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
