apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kraft-cluster-manage
    project: kraft
  name: kraft-cluster-manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraft-cluster-manage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kraft-cluster-manage
    spec:
      serviceAccountName: kraftsa
      automountServiceAccountToken: true
      containers:
      - image: "xelab04/kraft-cluster-manage:{{ .Chart.AppVersion }}"
        name: kraft-cluster-manage
        ports:
        - containerPort: 5000
        resources: {}

        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: jwtsecret
        - secretRef:
            name: database-secrets
status: {}
