{{- if .Values.hosted.enabled }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kraft-db
  name: kraft-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: kraft-db
{{- end }}
