apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kraft-resource-manage
    project: kraft
  name: kraft-resource-manage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kraft-resource-manage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kraft-resource-manage
    spec:
      serviceAccountName: kraftsa
      automountServiceAccountToken: true
      containers:
      - image: "xelab04/kraft-resource-manage:{{ .Chart.AppVersion }}"
        name: kraft-resource-manage
        ports:
        - containerPort: 5000
        resources: {}
status: {}
