apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kraft-resource-manage
  name: kraft-resource-manage
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kraft-resource-manage
status:
  loadBalancer: {}
